site_name: Canvas Proxy
site_description: База знаний сервиса Canvas Proxy
theme:
  name: material
  logo: https://raw.githubusercontent.com/CanvasProxy/assets/main/Logotipe-Canvas-Proxy-12.svg
  favicon: https://raw.githubusercontent.com/CanvasProxy/assets/main/Logotipe-Canvas-Proxy-12.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
  palette:
    - scheme: default
      primary: custom
      accent: custom
nav:
  - 🏠 Главная: index.md
  - 📦 Общие вопросы: general.md
  - 🛡 Белые списки: whitelist.md
  - ⚙️ Подключение: connection.md
  - 🛠 Частые проблемы: troubleshooting.md
  - 🎁 Партнерство: partnership.md
