site_name: Canvas Proxy
site_description: Официальная документация
theme:
  name: material
  logo: https://raw.githubusercontent.com/CanvasProxy/assets/main/Logotipe-Canvas-Proxy-12.svg
  favicon: https://raw.githubusercontent.com/CanvasProxy/assets/main/Logotipe-Canvas-Proxy-12.svg
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - toc.integrate
    - navigation.instant
    - navigation.instant.prefetch
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: black
      toggle:
        icon: material/brightness-7
        name: Переключить на темную тему
markdown_extensions:
  - admonition
  - toc:
      permalink: true
nav:
  - Главная: index.md
  - Общие вопросы: general.md
  - Белые списки: whitelist.md
  - Подключение: connection.md
  - Решение проблем: troubleshooting.md
  - Партнерство: partnership.md
extra:
  generator: false
